version: "3"

services:
  frontend:
    build:
      context: frontend
    restart: always
    ports:
      - "127.0.0.1:5000:5000"
  backend:
    build:
      context: backend
    restart: always
    ports:
      - "127.0.0.1:8080:8080"

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
